# Generated by Django 5.1.3 on 2024-12-28 01:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0002_fatwa_subscribedusers_article_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderr",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="wallentry_100",
            name="wall_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="wallentry_200",
            name="wall_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
